version: '3.3'
services:
    mern-auth:
      build: .
      image: mern-auth
      container_name: mern-auth
      volumes:
        - "./config:/opt/mern-auth/config"
      ports:
        - "5000:5000"
        - "3000:3000"
