version: '3.3'

services:
    mern-auth:
      build: .
      image: mern-auth
      container_name: mern-auth
      volumes:
#       - "/opt/test/docker_test:/app"
#       - "./routes/api:/app"
#        - "./config/:/opt/test/MERN-AUTH-ANSIBLE/config/"
        - "/home/patrick/Apps/MERN-AUTH-JENKS-K8S/config:/var/lib/jenkins/workspace/mern_docker/config"
      ports:
        - "5000:5000"
        - "3000:3000"
#        - "27017:27017"
    database: # name of the third service
      image: mongo:4.2.0 # specify image to build container from
#      ports:
#        - "27017:27017" # specify port forwarding

#      expose:
#        - "5000"
#        - "3000"
#        - "3333"
#        - "5555"
#    working_dir: /opt/test/docker_test

#    client:
#      build: .
#      volumes:
#        - "./client:/app"
#      ports:
#        - "3333:3000"
#      expose:
#        - "3000"
##      working_dir:
#      depends_on:
#        - api
