kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-claim2
  namespace: development
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
