apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#Create the PersistentVolumeClaim:
#kubectl apply -f https://k8s.io/examples/pods/storage/pv-claim.yaml

#Look again at the PersistentVolume:
#kubectl get pv task-pv-volume
