apiVersion: v1
kind: Service
metadata:
  name: mern-auth-service
  namespace: development
  labels:
    app: mern-auth
spec:
  selector:
    app: mern-auth
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
